FROM alpine:3.18 AS builder

ENV SYSBENCH_VERSION 1.0.20

RUN apk add --no-cache --update \
        bash-completion \
        autoconf \
        automake \
        build-base \
        git \
        libaio-dev \
        libtool \
        pkgconf \
        mariadb-dev \
        postgresql-dev

RUN git clone https://github.com/akopytov/sysbench.git --branch ${SYSBENCH_VERSION} --depth 1

WORKDIR /sysbench
RUN ./autogen.sh && \
    ./configure && \
    make -j && \
    make install

RUN rm -rf /sysbench
RUN apk del pkgconf git build-base automake autoconf libtool mariadb-dev postgresql-dev

ENTRYPOINT ["/usr/local/bin/sysbench"]
