version: '3'
services:
  mysql-master:
    ## mysql version, you could get more tags at here : https://hub.docker.com/_/mysql?tab=tags
    image: mysql:${MYSQL_VERSION}
    ## host port is 3306, you could change to 33060 or any other port doesn't conflict MySQL on your OS
    ports:
      - "13306:3306"
    container_name: shardingsphere-mysql-master
    command: [
      "--log-bin=mysql-bin",
      "--server-id=${MASTER_SERVER_ID}",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--innodb_flush_log_at_trx_commit=1",
      "--sync_binlog=1"
    ]
    ## launch mysql with password root
    ## you could access the mysql in container by following command :
    ## docker exec -it shardingsphere-mysql mysql -uroot -proot
    ## if you insist to use password in mysql, remove MYSQL_ALLOW_EMPTY_PASSWORD=yes and uncomment following args
    #  - MYSQL_ROOT_PASSWORD=root
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_USER_PASSWORD}
      - TZ=Asia/Shanghai
    volumes:
      - ../resources/database-init.sql:/docker-entrypoint-initdb.d/database-init.sql
      - ../resources/master-init.sql:/docker-entrypoint-initdb.d/master-init.sql

  mysql-slave-0:
    ## mysql version, you could get more tags at here : https://hub.docker.com/_/mysql?tab=tags
    image: mysql:${MYSQL_VERSION}
    ## host port is 3306, you could change to 33060 or any other port doesn't conflict MySQL on your OS
    ports:
      - "13307:3306"
    container_name: shardingsphere-mysql-slave-0
    command: [
      "--log-bin=mysql-bin",
      "--server-id=${SLAVE_SERVER_0_ID}",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--innodb_flush_log_at_trx_commit=0",
      "--sync_binlog=0"
    ]
    ## launch mysql with password root
    ## you could access the mysql in container by following command :
    ## docker exec -it shardingsphere-mysql mysql -uroot -proot
    ## if you insist to use password in mysql, remove MYSQL_ALLOW_EMPTY_PASSWORD=yes and uncomment following args
    #    #  - MYSQL_ROOT_PASSWORD=root_EMPTY_PASSWORD=yes and uncomment following args
    #  - MYSQL_ROOT_PASSWORD=root
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_USER_PASSWORD}
      - TZ=Asia/Shanghai
    volumes:
      - ../resources/slave-init.sql:/docker-entrypoint-initdb.d/slave-init.sql

  mysql-slave-1:
    ## mysql version, you could get more tags at here : https://hub.docker.com/_/mysql?tab=tags
    image: mysql:${MYSQL_VERSION}
    ## host port is 3306, you could change to 33060 or any other port doesn't conflict MySQL on your OS
    ports:
      - "13308:3306"
    container_name: shardingsphere-mysql-slave-1
    command: [
      "--log-bin=mysql-bin",
      "--server-id=${SLAVE_SERVER_1_ID}",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--innodb_flush_log_at_trx_commit=0",
      "--sync_binlog=0"
    ]
    ## launch mysql with password root
    ## you could access the mysql in container by following command :
    ## docker exec -it shardingsphere-mysql mysql -uroot -proot
    ## if you insist to use password in mysql, remove MYSQL_ALLOW_EMPTY_PASSWORD=yes and uncomment following args
    #  - MYSQL_ROOT_PASSWORD=root
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_USER_PASSWORD}
      - TZ=Asia/Shanghai
    volumes:
      - ../resources/slave-init.sql:/docker-entrypoint-initdb.d/slave-init.sql
